### ISSUE TITLE
PiShrink Error

### ISSUE THREAD

**Issue by iam-shanmukha** [ammababoi/PiShrink#6]
[androhack7r@evt5002 Documents]:( sudo pishrink device /dev/sda
calling parser
shrink V0.0 

insert source SD card and >>> close all popup file manager windows <<<
press [Enter] to continue, CTRL-C to abort

unmount ok

generate image from SD card
/usr/bin/pishrink: line 178: pv: command not found
image read ok

owner and group ok

ready

pishrink V0.0
pishrink: image.img ...
Error: The device /home/androhack7r/Documents/image.img is so small that it cannot possibly store a file system or partition table.  Perhaps you selected the wrong device?
Aborting due to errexit on line 466. Exit code: 1
pishrink: ERROR occurred in line image.img: parted failed with rc 1
pishrink: image.img ...

**Comment by mvrk33** [comment]
please install `sudo apt install pv`

**Comment by iam-shanmukha** [comment]
Thank You! Solved.
Pull request need with the above command in pishrink file
